### PR TITLE
Add snapshot tests, test GPG signatures and wheels

### PR DESCRIPTION
**Pull request by shepherdjerred**
* Add snapshot tests for our parser
* Add tests for wheels
* Add tests for GPG signatures
* Do not include `gpg_signature` in the metadata since Twine does not output that field

Related to https://github.com/rstudio/package-manager/issues/11950

### CODE REVIEW

**Review by jmwoliver — APPROVED** [review]
This is really great! I like all the discrepancies it helped us find.

I can't remember, is dependabot set up in a way that it will update the `twine` version that is used in the GHA for testing? I just want to make sure we are always testing against the latest version of `twine` to make sure our parsing is always correct.

**Comment by shepherdjerred** [comment]
> This is really great! I like all the discrepancies it helped us find.
> 
> I can't remember, is dependabot set up in a way that it will update the `twine` version that is used in the GHA for testing? I just want to make sure we are always testing against the latest version of `twine` to make sure our parsing is always correct.

We do a `pip install twine` on every run of the action, so the latest version will always run.

> Edit: should the GHA run daily and have errors output to the #ppm-bots channel?

Sure, we can try this.

**Comment by shepherdjerred** [comment]
@jmwoliver I've scheduled the action to run weekly. Failures use a Slack webhook to notify `#ppm-bots`.

CleanShot 2023-11-03 at 11 22 38@2x

**Comment by shepherdjerred** [comment]
I meant to enable auto-merge... whoops. I think everything was passing, though. I'll follow up and tag a new release once everything looks good.

**Comment by jmwoliver** [comment]
@shepherdjerred No worries, sounds good!

**Pull request merged**
